-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN; 
 ALTER TABLE IF EXISTS public.scenario DROP COLUMN IF EXISTS platform;

ALTER TABLE IF EXISTS public.scenario
    ADD COLUMN platform_id bigint;

ALTER TABLE IF EXISTS public.scenario
    ADD CONSTRAINT fklvweoi5rrnou42laed67664cx FOREIGN KEY (platform_id)
    REFERENCES public.platform (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

 END;