-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN; 

-- Create test_iteration_result table
CREATE TABLE IF NOT EXISTS public.test_iteration_result
(
    id bigint NOT NULL,
    version bigint NOT NULL,
    person_id bigint NOT NULL,
    date_created timestamp without time zone,
    notes character varying(1000) COLLATE pg_catalog."default",
    result character varying(7) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT test_iteration_result_pkey PRIMARY KEY (id),
    CONSTRAINT fkjeufa3succg1vu5dfbxlp4nvs FOREIGN KEY (person_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.test_iteration_result
    OWNER to everest_admin;

-- Create test_iteration_test_iteration_result join table
 CREATE TABLE IF NOT EXISTS public.test_iteration_test_iteration_result
(
    test_iteration_results_id bigint,
    test_iteration_result_id bigint,
    results_idx integer,
    CONSTRAINT fkqnjdxcmv1q5s908myyg4ipjpf FOREIGN KEY (test_iteration_result_id)
        REFERENCES public.test_iteration_result (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.test_iteration_test_iteration_result
    OWNER to everest_admin;

-- Create Platform table
CREATE TABLE IF NOT EXISTS public.platform
(
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT platform_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.platform
    OWNER to everest_admin;

-- Create project_platform join table
CREATE TABLE IF NOT EXISTS public.project_platform
(
    project_platforms_id bigint NOT NULL,
    platform_id bigint,
    CONSTRAINT fk2onc831nhy70kq6lir4spkbro FOREIGN KEY (project_platforms_id)
        REFERENCES public.project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fktojtw3mm0xkseif9ob7f7k5ch FOREIGN KEY (platform_id)
        REFERENCES public.platform (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.project_platform
    OWNER to everest_admin;

-- Alter test_case table
ALTER TABLE IF EXISTS public.test_case DROP COLUMN IF EXISTS platform;

ALTER TABLE IF EXISTS public.test_case
    ADD COLUMN platform_id bigint;

ALTER TABLE IF EXISTS public.test_case
    ADD CONSTRAINT fklqbobn44b6e9bar1la55tjlgn FOREIGN KEY (platform_id)
    REFERENCES public.platform (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Alter test_cycle table
ALTER TABLE IF EXISTS public.test_cycle DROP COLUMN IF EXISTS platform;

ALTER TABLE IF EXISTS public.test_cycle
    ADD COLUMN platform_id bigint;

ALTER TABLE IF EXISTS public.test_cycle
    ADD CONSTRAINT fkeaxi1ty8gdphuilhvwkfgjjba FOREIGN KEY (platform_id)
    REFERENCES public.platform (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Alter bug table
ALTER TABLE IF EXISTS public.bug DROP COLUMN IF EXISTS platform;

ALTER TABLE IF EXISTS public.bug
    ADD COLUMN platform_id bigint;

ALTER TABLE IF EXISTS public.bug
    ADD CONSTRAINT fkkd95wxftc12rtt25xmtfga0x1 FOREIGN KEY (platform_id)
    REFERENCES public.platform (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Alter test_iteration table
ALTER TABLE IF EXISTS public.test_iteration DROP COLUMN IF EXISTS date_executed;

ALTER TABLE IF EXISTS public.test_iteration DROP COLUMN IF EXISTS notes;

ALTER TABLE IF EXISTS public.test_iteration DROP COLUMN IF EXISTS person_id;

ALTER TABLE IF EXISTS public.test_iteration DROP COLUMN IF EXISTS result;

ALTER TABLE IF EXISTS public.test_iteration
    ADD COLUMN last_executed timestamp without time zone;

ALTER TABLE IF EXISTS public.test_iteration
    ADD COLUMN last_executed_by_id bigint;

ALTER TABLE IF EXISTS public.test_iteration
    ADD COLUMN last_result character varying(7) COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.test_iteration DROP CONSTRAINT IF EXISTS fkahonylro8iob3xuqpjf3xknlr;

ALTER TABLE IF EXISTS public.test_iteration
    ADD CONSTRAINT fkl64qw5fgkun83y603maxrxxji FOREIGN KEY (last_executed_by_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

 END;