-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN; 
 DROP TABLE IF EXISTS public.test_run_test_result CASCADE;
ALTER TABLE IF EXISTS public.release_plan
    ADD COLUMN notes character varying(1000) COLLATE pg_catalog."default";

DELETE FROM public.test_result;

ALTER TABLE IF EXISTS public.test_result
    ADD COLUMN test_run_id bigint NOT NULL;

ALTER TABLE IF EXISTS public.test_result
    ADD CONSTRAINT fkoqjh3usd009un5fv5wmg7vv96 FOREIGN KEY (test_run_id)
    REFERENCES public.test_run (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

 END;